# .air.toml

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go run ./Delivery"
  bin = "tmp/main.exe"
  full_bin = "false"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
